{{- if .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.clusterSecretStore.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.clusterSecretStore.serviceAccount.name }}
            namespace: {{ .Values.clusterSecretStore.serviceAccount.namespace }}
{{- end }}
